name: Build And Push Universal

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  build-amd64:
    uses: ./.github/workflows/build.yml
    with:
      runner: ubuntu-latest
      arch: amd64
      arch_label: AMD64
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  # build-arm64:
  #   uses: ./.github/workflows/build.yml
  #   with:
  #     runner: arm64_runner
  #     arch: arm64
  #     arch_label: ARM64
  #   secrets:
  #     DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
  #     DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
